### ISSUE TITLE
List of potential viewers

### ISSUE THREAD

**Issue by alphanaltinok** [EDRN/labcas-ui#110]

**Comment by alphanaltinok** [comment]
Some of the current viewers/libraries:

3D-Slicer	
https://www.slicer.org
open source, multiple languages (C++, Python, JS)
desktop app pretty much like ImageJ for medical images, supports DICOM
many plug-ins and extensions supported

QuPath		 
https://qupath.github.io
open source, mainly Java, utilizes ImageJ under the hood (?)
desktop whole slide viewer for biological images but no DICOM support 

medDream DICOM viewer
https://www.softneta.com/products/meddream-dicom-viewer/
full featured DICOM viewer, not open source
supports web deployment, integrates with PACS and open source
many security features built-in
examples at https://www.dicomlibrary.com

JS DICOM library
https://github.com/cornerstonejs/cornerstone
open source, basic DICOM viewer library on JS and HTML5
examples at their site

dwv DICOM Web Viewer
https://ivmartel.github.io/dwv/
open source, basic DICOM viewer library on JS and HTML5
examples at their site

Python DICOM library
https://pydicom.github.io
some example tutorial at
https://medium.com/@hengloose/a-comprehensive-starter-guide-to-visualizing-and-analyzing-dicom-images-in-python-7a8430fcb7ed

**Comment by yuliujpl** [comment]
It looks like DWV and JS DICOM might be libraries that can be natively embedded into Labcas-ui without further authentication (since it might be able to be embedded in the labcas-ui webpages).

Please let me know if you want me to evaluate for labcas 2.2

Thanks!
David

On Nov 11, 2020, at 11:04 AM, alphanaltinok <notifications@github.com<mailto:notifications@github.com>> wrote:



Some of the current viewers/libraries:

3D-Slicer
https://www.slicer.org<https://urldefense.us/v3/__https://www.slicer.org__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iBksnZq9$>
open source, multiple languages (C++, Python, JS)
desktop app pretty much like ImageJ for medical images, supports DICOM
many plug-ins and extensions supported

QuPath
https://qupath.github.io<https://urldefense.us/v3/__https://qupath.github.io__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iCvL_PjF$>
open source, mainly Java, utilizes ImageJ under the hood (?)
desktop whole slide viewer for biological images but no DICOM support

medDream DICOM viewer
https://www.softneta.com/products/meddream-dicom-viewer/<https://urldefense.us/v3/__https://www.softneta.com/products/meddream-dicom-viewer/__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iA-kL4d2$>
full featured DICOM viewer, not open source
supports web deployment, integrates with PACS and open source
many security features built-in
examples at https://www.dicomlibrary.com<https://urldefense.us/v3/__https://www.dicomlibrary.com__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iIOQXJMt$>

JS DICOM library
https://github.com/cornerstonejs/cornerstone<https://urldefense.us/v3/__https://github.com/cornerstonejs/cornerstone__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iOgsvtGp$>
open source, basic DICOM viewer library on JS and HTML5
examples at their site

dwv DICOM Web Viewer
https://ivmartel.github.io/dwv/<https://urldefense.us/v3/__https://ivmartel.github.io/dwv/__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iGmnd6U1$>
open source, basic DICOM viewer library on JS and HTML5
examples at their site

Python DICOM library
https://pydicom.github.io<https://urldefense.us/v3/__https://pydicom.github.io__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iClvNI4u$>
some example tutorial at
https://medium.com/@hengloose/a-comprehensive-starter-guide-to-visualizing-and-analyzing-dicom-images-in-python-7a8430fcb7ed<https://urldefense.us/v3/__https://medium.com/@hengloose/a-comprehensive-starter-guide-to-visualizing-and-analyzing-dicom-images-in-python-7a8430fcb7ed__;!!PvBDto6Hs4WbVuu7!e451mT9ba3FXrGUXYQCqZXZmoT6t00SFGukLdYR9uVeWA5b8kam37EFwc5d8iAys2jeq$>
