### ISSUE TITLE
Public collections section has 'no matching results' message

### ISSUE THREAD

**Issue by askarlupka** [EDRN/labcas-ui#150]
## 🐛 Bug Description

LabCAS Public collections section has a message of 'no matching results', although there are 20 collections available on the public site.

## 📜 How To Reproduce

1. Go to https://edrn-labcas.jpl.nasa.gov/labcas-ui/p/index.html
2. Compare to public collections available at: https://edrn-labcas.jpl.nasa.gov/labcas-ui/m/index.html

The bug appears both when logged in and not logged in.

## 🔎 Expected Behavior

Expectation was that public collections would appear in a table format.

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/54122306/189219316-eec315ca-db01-4ce4-8aa6-de864900a533.png)

## 🕵️‍♀️ Extra Details

Chrome: Version 105.0.5195.102 (Official Build) (64-bit), regular and incognito

**Comment by yuliujpl** [comment]
Will be taking a look at this and keeping you posted. Thank you

On Sep 8, 2022, at 1:34 PM, askarlupka ***@***.***> wrote:

﻿

🐛 Bug Description

LabCAS Public collections section has a message of 'no matching results', although there are 20 collections available on the public site.

📜 How To Reproduce

  1.  Go to https://edrn-labcas.jpl.nasa.gov/labcas-ui/p/index.html
  2.  Compare to public collections available at: https://edrn-labcas.jpl.nasa.gov/labcas-ui/m/index.html

The bug appears both when logged in and not logged in.

🔎 Expected Behavior

Expectation was that public collections would appear in a table format.

🖼 Screenshots

[image]<https://urldefense.us/v3/__https://user-images.githubusercontent.com/54122306/189219316-eec315ca-db01-4ce4-8aa6-de864900a533.png__;!!PvBDto6Hs4WbVuu7!fohDllnvWkuB8T3v4KB4sa5vwgAx5V9UDR3K61TRD1ZBnkCPxgSXQjduqCvInKBTsA-p$>

🕵️‍♀️ Extra Details

Chrome: Version 105.0.5195.102 (Official Build) (64-bit), regular and incognito

**Comment by yuliujpl** [comment]
This has been fixed, thanks so much @askarlupka for finding it!
