### ISSUE TITLE
Provide way to view OwnerPrincipal values for all Collections and Datasets

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#186]
## 🤔 Tell Us About the Feature
@yuliujpl Is there a way that the UI could provide an easy way for a "super user" or possibly just the IC Team to view OwnerPrincipal settings for all Collections and Datasets? It's getting difficult to manage all of the permissions with so much data.
Thanks,
Heather

**Comment by yuliujpl** [comment]
Yes! Please tell me which ownerprinciple I should watch out for and I can do the filtering to allow them to see the OwnerPrincipal metadata @hoodriverheather

**Comment by hoodriverheather** [comment]
@yuliujpl If users belonging to the SuperUser group could view the OwnerPrincipal and the DICOM tags you set for just my user (kincaid), that would be awesome. The OwnerPrincipal viewing would be at the Collection, Dataset and FileLevel. Let me know if this makes sense.

**Comment by hoodriverheather** [comment]
@yuliujpl The Super Users are not set at the OwnerPrincipal, rather the LDAP Group "Super User" is automatically given permission to see all Collections. I'm actually not sure how that happens or where it's set.
It would be great if you can actually allow this to be configurable, so that we can add other metadata to this list such as the DICOM values that my user can see, etc.

**Comment by yuliujpl** [comment]
Hi Heather, if it's ldap, then that's definitely still on the backend. The font-end client only filters out what's it provided by the permissions/api provided by the labcas-backend. I can certainly hide information but that would be custom code that's pseudo-hiding data that's otherwise accessible via that user's account!
________________________________
From: hoodriverheather ***@***.***>
Sent: Wednesday, April 3, 2024 5:03 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Provide way to view OwnerPrincipal values for all Collections and Datasets (Issue #186)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!OWAUcWOGPMV5FKIR7cgovT8ZE5q4E9vNibJAqMW84m3eXnMPNoxmQ0if19DaNo8wGDo10bJoGDd-ss8jAYFZ6Q9Wf-WM4Q$> The Super Users are not set at the OwnerPrincipal, rather the LDAP Group "Super User" is automatically given permission to see all Collections. I'm actually not sure how that happens or where it's set.
It would be great if you can actually allow this to be configurable, so that we can add other metadata to this list such as the DICOM values that my user can see, etc.

**Comment by hoodriverheather** [comment]
@yuliujpl OK. Dan is asking if you can make OwnerPrincipal visible only to my "kincaid" username for now and we can figure out the other way later. Would that work?
Thanks!

**Comment by hoodriverheather** [comment]
@yuliujpl can you look into making OwnerPrincipal viewable for my username "kincaid"?

**Comment by yuliujpl** [comment]
Done!

**Comment by hoodriverheather** [comment]
@yuliujpl Thanks!
