### ISSUE TITLE
19 collection-level files in LabCAS Solr but only 10 appear on labcas-ui

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#195]
## 🐛 Describe the Bug

In the [Lung Semantic Reader Study](https://mcl-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=ImageReaderStudy), 10 collection-level files appear:

<img width="634" alt="Screenshot of MCL LabCAS Image Reader Study" src="https://github.com/EDRN/labcas-ui/assets/814813/0b78c802-2525-412b-a365-d2369576b6df">

However, there are 19 files in Solr:

- `ImageReaderStudy/Documentation/Documentation-Illustrated Lexicon Terms.2023-12-24.pdf`
- `ImageReaderStudy/Documentation/Documentation-LabCASandZooniverseTrainingGuide.pdf`
- `ImageReaderStudy/Documentation/Documentation-Lung Illustrated Lexicon-Training Guide.2024.02.20.pptx`
- `ImageReaderStudy/Documentation/Documentation-Semantic Reader SW TipSheet.2024-07-28.pdf`
- `ImageReaderStudy/Documentation/Examples-Axial Location-Peripheral-Central-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Consistency-GGN-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Consistency-PSN-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Consistency-Semiconsolidation-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Consistency-SOLID-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-External-PleuralRetraction-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-External-SeptalStretch-Emphysema-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-External-VASCULAR CONVERGENCE-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Internal-Bubbles.Bronchograms-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Internal_AtypicalCyst-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Margins-Lobulated.Concavity-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Margins-PoorlyCircumscribed-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Margins-Serrated-Spiculated-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Margins-Smooth-FINAL.pdf`
- `ImageReaderStudy/Documentation/Examples-Shape-FINAL.pdf`

Is this discrepancy an issue with the UI or something else?

## 🕵️‍♀️ Extra Details

Incognito (private browsing) was engaged.

**Comment by yuliujpl** [comment]
Fixed, it's because of pagination, only shows the first 10 items. Sorry!
________________________________
From: Sean Kelly ***@***.***>
Sent: Monday, April 8, 2024 12:19 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [EDRN/labcas-ui] 19 collection-level files in LabCAS Solr but only 10 appear on labcas-ui (Issue #195)


🐛 Describe the Bug

In the Lung Semantic Reader Study<https://mcl-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=ImageReaderStudy>, 10 collection-level files appear:

Screenshot.2024-04-08.at.2.17.20.PM.png (view on web)<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/assets/814813/0b78c802-2525-412b-a365-d2369576b6df__;!!PvBDto6Hs4WbVuu7!KEF6CMRmaePFJyME_55qzz3MsANM4cCLaBSNJ9eh24rX0kfEs9PFG4DNKC1YW1iu8QQuuvZga1D2jnjLvE1iDzaDatwTYQ$>

However, there are 19 files in Solr:

  *   ImageReaderStudy/Documentation/Documentation-Illustrated Lexicon Terms.2023-12-24.pdf
  *   ImageReaderStudy/Documentation/Documentation-LabCASandZooniverseTrainingGuide.pdf
  *   ImageReaderStudy/Documentation/Documentation-Lung Illustrated Lexicon-Training Guide.2024.02.20.pptx
  *   ImageReaderStudy/Documentation/Documentation-Semantic Reader SW TipSheet.2024-07-28.pdf
  *   ImageReaderStudy/Documentation/Examples-Axial Location-Peripheral-Central-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Consistency-GGN-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Consistency-PSN-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Consistency-Semiconsolidation-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Consistency-SOLID-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-External-PleuralRetraction-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-External-SeptalStretch-Emphysema-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-External-VASCULAR CONVERGENCE-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Internal-Bubbles.Bronchograms-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Internal_AtypicalCyst-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Margins-Lobulated.Concavity-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Margins-PoorlyCircumscribed-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Margins-Serrated-Spiculated-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Margins-Smooth-FINAL.pdf
  *   ImageReaderStudy/Documentation/Examples-Shape-FINAL.pdf

Is this discrepancy an issue with the UI or something else?

**Comment by nutjob4life** [comment]
@yuliujpl thanks, glad it was an easy fix.

@hoodriverheather, I've now removed the collection-level files from `ImageReaderStudy`.
