### ISSUE TITLE
Add blue left menu bar to LabCAS login page. Include Announcements and New on menu.

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#196]
@yuliujpl Please add the left blue menu bar to the LabCAS login page. This update could be for the Core LabCAS (both NIST and EDRN). 

I may have requested this before, let me know if this isn't possible.

Dan would like to add a new menu option:
Announcements and News - this would be a new page where we can post LabCAS specific announcements. This could link to a Wagtail page if that's easiest, we should discuss with @nutjob4life.

**Comment by yuliujpl** [comment]
Done! Can you please let me know what the announcement url is? I can add new icon and link it anytime!
________________________________
From: hoodriverheather ***@***.***>
Sent: Thursday, April 18, 2024 8:47 AM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [EDRN/labcas-ui] Add blue left menu bar to LabCAS login page. Include Announcements and New on menu. (Issue #196)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!ISqnBePHsdU2mxpt5wLTpDXOSrRFabwamzNRTuRGYTjmysOR_TN7HPv5tqSw6Pr7tDNfpiwhTuU69EmoM2GiH1vL7PzsrA$> Please add the left blue menu bar to the LabCAS login page. This update could be for the Core LabCAS (both NIST and EDRN).

I may have requested this before, let me know if this isn't possible.

Dan would like to add a new menu option:
Announcements and News - this would be a new page where we can post LabCAS specific announcements. This could link to a Wagtail page if that's easiest, we should discuss with @nutjob4life<https://urldefense.us/v3/__https://github.com/nutjob4life__;!!PvBDto6Hs4WbVuu7!ISqnBePHsdU2mxpt5wLTpDXOSrRFabwamzNRTuRGYTjmysOR_TN7HPv5tqSw6Pr7tDNfpiwhTuU69EmoM2GiH1vBIdlNPA$>.

**Comment by nutjob4life** [comment]
@yuliujpl thanks for tackling this!

Remember how we talked about creating `nist`, `edrn`, and `mcl` branches in the git repository? It'd be really cool if we could link closing of an issue to a commit into one of those branches that shows how the fix was made.

This would be helpful for collaborators so they could see how it works and also contributes to the maturity of the codebase.

GitHub makes this easy, too: if your commit message is `Resolves #196`, for example, the GitHub will automatically close issue №196 and make the link to the commit for you.

**Comment by hoodriverheather** [comment]
@yuliujpl Thanks! I just sent Dan and email to see if he has a specific announcement he would like to add.

**Comment by hoodriverheather** [comment]
@yuliujpl He said he would like to add an announcement when we turn on authentication to download. :)
