### ISSUE TITLE
LTP2 Image Viewer not working in LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#234]
## 🐛 Describe the Bug

Getting the following error when using image viewer for this specific collection - GET https://edrn-labcas.jpl.nasa.gov/data-access-api/download?id=Lung_Team_Project_2/Images_Site_weRc6TUHvOru6A/b/2018-07-30/4/IMG100 404 (Unknown Reason)

This seems to be happening for any image i try to open in this collection - https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Lung_Team_Project_2

Other collections with images seem to open fine. I also had Emily confirm the same behavior.
<img width="1412" alt="Screenshot 2024-10-31 at 8 35 05 AM" src="https://github.com/user-attachments/assets/c1a77793-c589-4679-a1e9-1f99f3cd0fc4">

**Comment by yuliujpl** [comment]
It's because the ID is malformed:
[cid:d3749d6d-6132-47fd-bd0e-b121bff15dc5]

Somehow the ingest, if you look at the id row, it's missing the _09510935.dcm!

________________________________
From: hoodriverheather ***@***.***>
Sent: Wednesday, October 30, 2024 5:24 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [EDRN/labcas-ui] LTP2 Image Viewer not working in LabCAS (Issue #234)


🐛 Describe the Bug

Getting the following error when using image viewer for this specific collection - GET https://edrn-labcas.jpl.nasa.gov/data-access-api/download?id=Lung_Team_Project_2/Images_Site_weRc6TUHvOru6A/b/2018-07-30/4/IMG100 404 (Unknown Reason)

This seems to be happening for any image i try to open in this collection - https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Lung_Team_Project_2

Other collections with images seem to open fine. I also had Emily confirm the same behavior.
Screenshot.2024-10-30.at.1.33.04.PM.png (view on web)<https://urldefense.us/v3/__https://github.com/user-attachments/assets/1b86d36e-149f-4d73-9017-f026e372c9f3__;!!PvBDto6Hs4WbVuu7!M5dJmQUGj4Z7LhnPhXwN6rll7RGLDYT3FkZOQ9O8wW6uiYhCTwSLVlHYSEFGsxvG97Hy0Q_BYBI1YbPmPMv9pS-yFXzMTw$>

**Comment by hoodriverheather** [comment]
@nutjob4life Can you take a look at this issue? This is only happening with Lung Team Project 2 Collection on Prod.
    https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Lung_Team_Project_2

**Comment by nutjob4life** [comment]
@yuliujpl I'm not seeing it; which ID is malformed and what should it be?

**Comment by nutjob4life** [comment]
@hoodriverheather try it now

**Comment by hoodriverheather** [comment]
@nutjob4life Its' working on Prod :) 
Can you also make this update to Dev?

**Comment by nutjob4life** [comment]
@hoodriverheather the issue was not with Solr metadata but with file layouts. Since both prod and dev use the same files, if it's working on one it should be working on the other.

(Besides, it's just _dev_ … who cares, right? 🤔)

**Comment by hoodriverheather** [comment]
@nutjob4life LOL!
I actually really need this to work on dev so i can test the images you published from UCLA/VA. Here's a screenshot. Looks like same problem that was happening in Prod, only with LTP2.
Thanks!
<img width="1443" alt="Screenshot 2024-11-01 at 3 28 07 PM" src="https://github.com/user-attachments/assets/34a0525c-6c15-4e3e-bbc3-ed99197c3baa">

**Comment by nutjob4life** [comment]
Oh you're killing me @hoodriverheather  … no taking off early on Friday!

**Comment by hoodriverheather** [comment]
@nutjob4life - I know, i'm so mean! I'm fine if this gets fixed on Monday. :) Have a great weekend!

**Comment by nutjob4life** [comment]
@hoodriverheather try it now; I spot-checked a few files and they downloaded for me

Now for the next hour, I'm watching _GBBO_ and I don't want to know if you even exist! 😝
